### ISSUE TITLE
suo5连接失败

### ISSUE THREAD

**Issue by Axianke** [altEr1125/ShiroAttack2#1]
第一次成功后闪退，在连接就连不上了
<img width="816" alt="image" src="https://github.com/altEr1125/ShiroAttack2/assets/60959602/53d8dd47-5c02-4df0-8324-75225b25444f">

**Comment by altEr1125** [comment]
这个问题应该是suo5代理的问题，suo5的issues里有提过同样的问题，https://github.com/zema1/suo5/issues/16
