### ISSUE TITLE
新增内存马注入请求方式

### ISSUE THREAD

**Issue by izj007** [altEr1125/ShiroAttack2#2]
目前遇到一个环境，无法执行POST请求，不是waf的原因，能否使用其他请求方式，譬如put get之类的

**Comment by altEr1125** [comment]
> 目前遇到一个环境，无法执行POST请求，不是waf的原因，能否使用其他请求方式，譬如put get之类的

<img width="180" alt="image" src="https://github.com/altEr1125/ShiroAttack2/assets/75016675/244bcb58-86bb-46b3-b2be-918aba62e465">
这里可以选择GET/POST
